name: ci

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup_rust
        uses: dtolnay/rust-toolchain@stable

      - name: fmt
        run: cargo fmt --check

      - name: clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: test
        run: cargo test
