name: ci

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-15-intel
          - macos-15

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup_rust
        uses: dtolnay/rust-toolchain@stable

      - name: fmt
        run: cargo fmt --check

      - name: clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: test
        run: cargo test

      - name: build_release
        run: cargo build --release
